# Generated by Django 4.1.3 on 2022-12-13 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_todos_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='time',
        ),
    ]
